// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// feature_engineering.cpp
doubles_matrix<> compute_lags_cpp(doubles x, integers lags);
extern "C" SEXP _chronofeat_compute_lags_cpp(SEXP x, SEXP lags) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_lags_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<integers>>(lags)));
  END_CPP11
}
// feature_engineering.cpp
doubles_matrix<> compute_ma_cpp(doubles x, integers windows);
extern "C" SEXP _chronofeat_compute_ma_cpp(SEXP x, SEXP windows) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_ma_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<integers>>(windows)));
  END_CPP11
}
// feature_engineering.cpp
doubles_matrix<> compute_rollsum_cpp(doubles x, integers windows);
extern "C" SEXP _chronofeat_compute_rollsum_cpp(SEXP x, SEXP windows) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_rollsum_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<integers>>(windows)));
  END_CPP11
}
// feature_engineering.cpp
doubles_matrix<> compute_rollsd_cpp(doubles x, integers windows);
extern "C" SEXP _chronofeat_compute_rollsd_cpp(SEXP x, SEXP windows) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_rollsd_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<integers>>(windows)));
  END_CPP11
}
// feature_engineering.cpp
doubles_matrix<> compute_rollminmax_cpp(doubles x, integers windows, bool compute_min);
extern "C" SEXP _chronofeat_compute_rollminmax_cpp(SEXP x, SEXP windows, SEXP compute_min) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_rollminmax_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<integers>>(windows), cpp11::as_cpp<cpp11::decay_t<bool>>(compute_min)));
  END_CPP11
}
// feature_engineering.cpp
doubles_matrix<> compute_rollslope_cpp(doubles x, integers windows);
extern "C" SEXP _chronofeat_compute_rollslope_cpp(SEXP x, SEXP windows) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_rollslope_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<integers>>(windows)));
  END_CPP11
}
// feature_engineering.cpp
list make_target_feats_cpp(doubles y_hist, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows);
extern "C" SEXP _chronofeat_make_target_feats_cpp(SEXP y_hist, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows) {
  BEGIN_CPP11
    return cpp11::as_sexp(make_target_feats_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(y_hist), cpp11::as_cpp<cpp11::decay_t<SEXP>>(p), cpp11::as_cpp<cpp11::decay_t<SEXP>>(q), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_stats), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_windows)));
  END_CPP11
}
// recursive_forecast.cpp
doubles recursive_forecast_simple_cpp(doubles y_hist, doubles model_coef, bool has_intercept, int h, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees);
extern "C" SEXP _chronofeat_recursive_forecast_simple_cpp(SEXP y_hist, SEXP model_coef, SEXP has_intercept, SEXP h, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees) {
  BEGIN_CPP11
    return cpp11::as_sexp(recursive_forecast_simple_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(y_hist), cpp11::as_cpp<cpp11::decay_t<doubles>>(model_coef), cpp11::as_cpp<cpp11::decay_t<bool>>(has_intercept), cpp11::as_cpp<cpp11::decay_t<int>>(h), cpp11::as_cpp<cpp11::decay_t<SEXP>>(p), cpp11::as_cpp<cpp11::decay_t<SEXP>>(q), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_stats), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_degrees)));
  END_CPP11
}
// recursive_forecast.cpp
doubles_matrix<> build_features_recursive_cpp(doubles y_hist, int h, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees, SEXP y_future);
extern "C" SEXP _chronofeat_build_features_recursive_cpp(SEXP y_hist, SEXP h, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees, SEXP y_future) {
  BEGIN_CPP11
    return cpp11::as_sexp(build_features_recursive_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(y_hist), cpp11::as_cpp<cpp11::decay_t<int>>(h), cpp11::as_cpp<cpp11::decay_t<SEXP>>(p), cpp11::as_cpp<cpp11::decay_t<SEXP>>(q), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_stats), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_degrees), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y_future)));
  END_CPP11
}
// recursive_forecast.cpp
doubles forecast_iterative_cpp(doubles y_hist, int h, cpp11::function predict_fn, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees, int batch_size);
extern "C" SEXP _chronofeat_forecast_iterative_cpp(SEXP y_hist, SEXP h, SEXP predict_fn, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees, SEXP batch_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(forecast_iterative_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(y_hist), cpp11::as_cpp<cpp11::decay_t<int>>(h), cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(predict_fn), cpp11::as_cpp<cpp11::decay_t<SEXP>>(p), cpp11::as_cpp<cpp11::decay_t<SEXP>>(q), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_stats), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_degrees), cpp11::as_cpp<cpp11::decay_t<int>>(batch_size)));
  END_CPP11
}
// recursive_forecast.cpp
doubles_matrix<> recursive_forecast_groups_cpp(doubles_matrix<> y_matrix, doubles model_coef, bool has_intercept, int h, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees);
extern "C" SEXP _chronofeat_recursive_forecast_groups_cpp(SEXP y_matrix, SEXP model_coef, SEXP has_intercept, SEXP h, SEXP p, SEXP q, SEXP roll_windows, SEXP roll_stats, SEXP trend_windows, SEXP trend_degrees) {
  BEGIN_CPP11
    return cpp11::as_sexp(recursive_forecast_groups_cpp(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(y_matrix), cpp11::as_cpp<cpp11::decay_t<doubles>>(model_coef), cpp11::as_cpp<cpp11::decay_t<bool>>(has_intercept), cpp11::as_cpp<cpp11::decay_t<int>>(h), cpp11::as_cpp<cpp11::decay_t<SEXP>>(p), cpp11::as_cpp<cpp11::decay_t<SEXP>>(q), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(roll_stats), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_windows), cpp11::as_cpp<cpp11::decay_t<SEXP>>(trend_degrees)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_chronofeat_build_features_recursive_cpp",  (DL_FUNC) &_chronofeat_build_features_recursive_cpp,   9},
    {"_chronofeat_compute_lags_cpp",              (DL_FUNC) &_chronofeat_compute_lags_cpp,               2},
    {"_chronofeat_compute_ma_cpp",                (DL_FUNC) &_chronofeat_compute_ma_cpp,                 2},
    {"_chronofeat_compute_rollminmax_cpp",        (DL_FUNC) &_chronofeat_compute_rollminmax_cpp,         3},
    {"_chronofeat_compute_rollsd_cpp",            (DL_FUNC) &_chronofeat_compute_rollsd_cpp,             2},
    {"_chronofeat_compute_rollslope_cpp",         (DL_FUNC) &_chronofeat_compute_rollslope_cpp,          2},
    {"_chronofeat_compute_rollsum_cpp",           (DL_FUNC) &_chronofeat_compute_rollsum_cpp,            2},
    {"_chronofeat_forecast_iterative_cpp",        (DL_FUNC) &_chronofeat_forecast_iterative_cpp,        10},
    {"_chronofeat_make_target_feats_cpp",         (DL_FUNC) &_chronofeat_make_target_feats_cpp,          6},
    {"_chronofeat_recursive_forecast_groups_cpp", (DL_FUNC) &_chronofeat_recursive_forecast_groups_cpp, 10},
    {"_chronofeat_recursive_forecast_simple_cpp", (DL_FUNC) &_chronofeat_recursive_forecast_simple_cpp, 10},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_chronofeat(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
