// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_lags_cpp
NumericMatrix compute_lags_cpp(NumericVector x, IntegerVector lags);
RcppExport SEXP _chronofeat_compute_lags_cpp(SEXP xSEXP, SEXP lagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lags(lagsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_lags_cpp(x, lags));
    return rcpp_result_gen;
END_RCPP
}
// compute_ma_cpp
NumericMatrix compute_ma_cpp(NumericVector x, IntegerVector windows);
RcppExport SEXP _chronofeat_compute_ma_cpp(SEXP xSEXP, SEXP windowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type windows(windowsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ma_cpp(x, windows));
    return rcpp_result_gen;
END_RCPP
}
// compute_rollsum_cpp
NumericMatrix compute_rollsum_cpp(NumericVector x, IntegerVector windows);
RcppExport SEXP _chronofeat_compute_rollsum_cpp(SEXP xSEXP, SEXP windowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type windows(windowsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rollsum_cpp(x, windows));
    return rcpp_result_gen;
END_RCPP
}
// compute_rollsd_cpp
NumericMatrix compute_rollsd_cpp(NumericVector x, IntegerVector windows);
RcppExport SEXP _chronofeat_compute_rollsd_cpp(SEXP xSEXP, SEXP windowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type windows(windowsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rollsd_cpp(x, windows));
    return rcpp_result_gen;
END_RCPP
}
// compute_rollminmax_cpp
NumericMatrix compute_rollminmax_cpp(NumericVector x, IntegerVector windows, bool compute_min);
RcppExport SEXP _chronofeat_compute_rollminmax_cpp(SEXP xSEXP, SEXP windowsSEXP, SEXP compute_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type windows(windowsSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_min(compute_minSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rollminmax_cpp(x, windows, compute_min));
    return rcpp_result_gen;
END_RCPP
}
// compute_rollslope_cpp
NumericMatrix compute_rollslope_cpp(NumericVector x, IntegerVector windows);
RcppExport SEXP _chronofeat_compute_rollslope_cpp(SEXP xSEXP, SEXP windowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type windows(windowsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rollslope_cpp(x, windows));
    return rcpp_result_gen;
END_RCPP
}
// make_target_feats_cpp
List make_target_feats_cpp(NumericVector y_hist, Nullable<int> p, Nullable<IntegerVector> q, Nullable<IntegerVector> roll_windows, Nullable<CharacterVector> roll_stats, Nullable<IntegerVector> trend_windows);
RcppExport SEXP _chronofeat_make_target_feats_cpp(SEXP y_histSEXP, SEXP pSEXP, SEXP qSEXP, SEXP roll_windowsSEXP, SEXP roll_statsSEXP, SEXP trend_windowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_hist(y_histSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type p(pSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type q(qSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type roll_windows(roll_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type roll_stats(roll_statsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_windows(trend_windowsSEXP);
    rcpp_result_gen = Rcpp::wrap(make_target_feats_cpp(y_hist, p, q, roll_windows, roll_stats, trend_windows));
    return rcpp_result_gen;
END_RCPP
}
// recursive_forecast_simple_cpp
NumericVector recursive_forecast_simple_cpp(NumericVector y_hist, NumericVector model_coef, bool has_intercept, int h, Nullable<IntegerVector> p, Nullable<IntegerVector> q, Nullable<IntegerVector> roll_windows, Nullable<CharacterVector> roll_stats, Nullable<IntegerVector> trend_windows, Nullable<IntegerVector> trend_degrees);
RcppExport SEXP _chronofeat_recursive_forecast_simple_cpp(SEXP y_histSEXP, SEXP model_coefSEXP, SEXP has_interceptSEXP, SEXP hSEXP, SEXP pSEXP, SEXP qSEXP, SEXP roll_windowsSEXP, SEXP roll_statsSEXP, SEXP trend_windowsSEXP, SEXP trend_degreesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_hist(y_histSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type model_coef(model_coefSEXP);
    Rcpp::traits::input_parameter< bool >::type has_intercept(has_interceptSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type p(pSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type q(qSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type roll_windows(roll_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type roll_stats(roll_statsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_windows(trend_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_degrees(trend_degreesSEXP);
    rcpp_result_gen = Rcpp::wrap(recursive_forecast_simple_cpp(y_hist, model_coef, has_intercept, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees));
    return rcpp_result_gen;
END_RCPP
}
// build_features_recursive_cpp
NumericMatrix build_features_recursive_cpp(NumericVector y_hist, int h, Nullable<IntegerVector> p, Nullable<IntegerVector> q, Nullable<IntegerVector> roll_windows, Nullable<CharacterVector> roll_stats, Nullable<IntegerVector> trend_windows, Nullable<IntegerVector> trend_degrees, Nullable<NumericVector> y_future);
RcppExport SEXP _chronofeat_build_features_recursive_cpp(SEXP y_histSEXP, SEXP hSEXP, SEXP pSEXP, SEXP qSEXP, SEXP roll_windowsSEXP, SEXP roll_statsSEXP, SEXP trend_windowsSEXP, SEXP trend_degreesSEXP, SEXP y_futureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_hist(y_histSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type p(pSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type q(qSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type roll_windows(roll_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type roll_stats(roll_statsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_windows(trend_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_degrees(trend_degreesSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type y_future(y_futureSEXP);
    rcpp_result_gen = Rcpp::wrap(build_features_recursive_cpp(y_hist, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees, y_future));
    return rcpp_result_gen;
END_RCPP
}
// forecast_iterative_cpp
NumericVector forecast_iterative_cpp(NumericVector y_hist, int h, Function predict_fn, Nullable<IntegerVector> p, Nullable<IntegerVector> q, Nullable<IntegerVector> roll_windows, Nullable<CharacterVector> roll_stats, Nullable<IntegerVector> trend_windows, Nullable<IntegerVector> trend_degrees, int batch_size);
RcppExport SEXP _chronofeat_forecast_iterative_cpp(SEXP y_histSEXP, SEXP hSEXP, SEXP predict_fnSEXP, SEXP pSEXP, SEXP qSEXP, SEXP roll_windowsSEXP, SEXP roll_statsSEXP, SEXP trend_windowsSEXP, SEXP trend_degreesSEXP, SEXP batch_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_hist(y_histSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< Function >::type predict_fn(predict_fnSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type p(pSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type q(qSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type roll_windows(roll_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type roll_stats(roll_statsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_windows(trend_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_degrees(trend_degreesSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_iterative_cpp(y_hist, h, predict_fn, p, q, roll_windows, roll_stats, trend_windows, trend_degrees, batch_size));
    return rcpp_result_gen;
END_RCPP
}
// recursive_forecast_groups_cpp
NumericMatrix recursive_forecast_groups_cpp(NumericMatrix y_matrix, NumericVector model_coef, bool has_intercept, int h, Nullable<IntegerVector> p, Nullable<IntegerVector> q, Nullable<IntegerVector> roll_windows, Nullable<CharacterVector> roll_stats, Nullable<IntegerVector> trend_windows, Nullable<IntegerVector> trend_degrees);
RcppExport SEXP _chronofeat_recursive_forecast_groups_cpp(SEXP y_matrixSEXP, SEXP model_coefSEXP, SEXP has_interceptSEXP, SEXP hSEXP, SEXP pSEXP, SEXP qSEXP, SEXP roll_windowsSEXP, SEXP roll_statsSEXP, SEXP trend_windowsSEXP, SEXP trend_degreesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y_matrix(y_matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type model_coef(model_coefSEXP);
    Rcpp::traits::input_parameter< bool >::type has_intercept(has_interceptSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type p(pSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type q(qSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type roll_windows(roll_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type roll_stats(roll_statsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_windows(trend_windowsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type trend_degrees(trend_degreesSEXP);
    rcpp_result_gen = Rcpp::wrap(recursive_forecast_groups_cpp(y_matrix, model_coef, has_intercept, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chronofeat_compute_lags_cpp", (DL_FUNC) &_chronofeat_compute_lags_cpp, 2},
    {"_chronofeat_compute_ma_cpp", (DL_FUNC) &_chronofeat_compute_ma_cpp, 2},
    {"_chronofeat_compute_rollsum_cpp", (DL_FUNC) &_chronofeat_compute_rollsum_cpp, 2},
    {"_chronofeat_compute_rollsd_cpp", (DL_FUNC) &_chronofeat_compute_rollsd_cpp, 2},
    {"_chronofeat_compute_rollminmax_cpp", (DL_FUNC) &_chronofeat_compute_rollminmax_cpp, 3},
    {"_chronofeat_compute_rollslope_cpp", (DL_FUNC) &_chronofeat_compute_rollslope_cpp, 2},
    {"_chronofeat_make_target_feats_cpp", (DL_FUNC) &_chronofeat_make_target_feats_cpp, 6},
    {"_chronofeat_recursive_forecast_simple_cpp", (DL_FUNC) &_chronofeat_recursive_forecast_simple_cpp, 10},
    {"_chronofeat_build_features_recursive_cpp", (DL_FUNC) &_chronofeat_build_features_recursive_cpp, 9},
    {"_chronofeat_forecast_iterative_cpp", (DL_FUNC) &_chronofeat_forecast_iterative_cpp, 10},
    {"_chronofeat_recursive_forecast_groups_cpp", (DL_FUNC) &_chronofeat_recursive_forecast_groups_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_chronofeat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
