# Generated by cpp11: do not edit by hand

compute_lags_cpp <- function(x, lags) {
  .Call(`_chronofeat_compute_lags_cpp`, x, lags)
}

compute_ma_cpp <- function(x, windows) {
  .Call(`_chronofeat_compute_ma_cpp`, x, windows)
}

compute_rollsum_cpp <- function(x, windows) {
  .Call(`_chronofeat_compute_rollsum_cpp`, x, windows)
}

compute_rollsd_cpp <- function(x, windows) {
  .Call(`_chronofeat_compute_rollsd_cpp`, x, windows)
}

compute_rollminmax_cpp <- function(x, windows, compute_min) {
  .Call(`_chronofeat_compute_rollminmax_cpp`, x, windows, compute_min)
}

compute_rollslope_cpp <- function(x, windows) {
  .Call(`_chronofeat_compute_rollslope_cpp`, x, windows)
}

make_target_feats_cpp <- function(y_hist, p, q, roll_windows, roll_stats, trend_windows) {
  .Call(`_chronofeat_make_target_feats_cpp`, y_hist, p, q, roll_windows, roll_stats, trend_windows)
}

recursive_forecast_simple_cpp <- function(y_hist, model_coef, has_intercept, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees) {
  .Call(`_chronofeat_recursive_forecast_simple_cpp`, y_hist, model_coef, has_intercept, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees)
}

build_features_recursive_cpp <- function(y_hist, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees, y_future) {
  .Call(`_chronofeat_build_features_recursive_cpp`, y_hist, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees, y_future)
}

forecast_iterative_cpp <- function(y_hist, h, predict_fn, p, q, roll_windows, roll_stats, trend_windows, trend_degrees, batch_size) {
  .Call(`_chronofeat_forecast_iterative_cpp`, y_hist, h, predict_fn, p, q, roll_windows, roll_stats, trend_windows, trend_degrees, batch_size)
}

recursive_forecast_groups_cpp <- function(y_matrix, model_coef, has_intercept, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees) {
  .Call(`_chronofeat_recursive_forecast_groups_cpp`, y_matrix, model_coef, has_intercept, h, p, q, roll_windows, roll_stats, trend_windows, trend_degrees)
}
